backend:
  name: git-gateway
  branch: main

local_backend: true

publish_mode: editorial_workflow

media_folder: "assets/templates"
public_folder: "/assets/templates"

collections:
  - name: "events" 
    label: "Events"
    label_singular: "Event"
    folder: "_events"
    create: true
    slug: "{{date}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL slug" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD" }
      - { label: "Status", name: "status", widget: "select", options: ["active", "closed"], default: "active" }
      - { label: "Certificate Template", name: "template", widget: "image" }
      - { label: "Firestore Collection", name: "firestore_collection", widget: "string", hint: "Firestore collection/doc id" }
      - { label: "Keywords", name: "keywords", widget: "string", default: "RSA Certify, Certificate Center, Rotaract South Asia MDIO, Achievement Certificates, Digital Certificates, Rotaract Activities, Certificate Generation, RSAMDIO", hint: "Comma-separated keywords for SEO" }
      - { label: "Author", name: "author", widget: "string", default: "Rotaract South Asia MDIO", hint: "Event organizer or author" }
      - { label: "OG Type", name: "og_type", widget: "string", default: "event", hint: "Open Graph type (e.g., event)" }
      - { label: "OG Image", name: "og_image", widget: "image", default: "/assets/images/calculatorogimg.webp", hint: "Open Graph image for social sharing" }
      - { label: "Schema Type", name: "schema_type", widget: "string", default: "Event", hint: "Schema.org type for structured data" }
      - { label: "Robots", name: "robots", widget: "string", default: "index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1", hint: "SEO robots meta tag content" }
      - label: "Certificate Fields"
        name: "participantFields"
        widget: "list"
        summary: "{{fields.label}} ({{fields.key}})"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Label", name: "label", widget: "string" }
          - { label: "Required", name: "required", widget: "boolean", default: false }
          - { label: "X Position (%)", name: "x", widget: "string", default: "20%", hint: "Horizontal position as percentage" }
          - { label: "Y Position (px)", name: "y", widget: "number", default: 350, hint: "Vertical position in pixels" }
          - { label: "Font Size", name: "font_size", widget: "number", default: 50, hint: "Font size in pixels" }
          - { label: "Font Family", name: "font_family", widget: "string", default: "Arial" }
          - { label: "Color", name: "color", widget: "string", default: "#000000", hint: "Hex color code" }
          - { label: "Width (%)", name: "width", widget: "string", default: "60%", hint: "Width as percentage" }
          - { label: "Height (px)", name: "height", widget: "number", default: 50, hint: "Height in pixels" }
          - { label: "Text Align", name: "text_align", widget: "select", options: ["left", "center", "right"], default: "center" }