backend:
  name: git-gateway
  branch: main

local_backend: true

publish_mode: editorial_workflow

media_folder: "assets/templates"
public_folder: "/assets/templates"

collections:
  - name: "events" 
    label: "Events"
    label_singular: "Event"
    folder: "_events"
    create: true
    slug: "{{date}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "URL slug" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD" }
      - { label: "Status", name: "status", widget: "select", options: ["active", "closed"], default: "active" }
      - {label: "Certificate Template", name: "template", widget: "image"}
      - { label: "Firestore Collection", name: "firestore_collection", widget: "string", hint: "Firestore collection/doc id" }
      - label: "Participant Fields"
        name: "participantFields"
        widget: "list"
        summary: "{{fields.label}} ({{fields.key}})"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Label", name: "label", widget: "string" }
          - { label: "Required", name: "required", widget: "boolean", default: false }
          - { label: "X Position (%)", name: "x", widget: "string", hint: "Horizontal position as percentage" }
          - { label: "Y Position (px)", name: "y", widget: "number", hint: "Vertical position in pixels" }
          - { label: "Font Size", name: "font_size", widget: "number", default: 50 }
          - { label: "Font Family", name: "font_family", widget: "string", default: "Arial" }
          - { label: "Color", name: "color", widget: "string", default: "#000000", hint: "Hex color code" }
          - { label: "Width (%)", name: "width", widget: "string", hint: "Width as percentage" }
          - { label: "Height (px)", name: "height", widget: "number", default: 50 }
          - { label: "Text Align", name: "text_align", widget: "select", options: ["left", "center", "right"], default: "center" }